[build]
  command = "CI=false npm run build"
  publish = "dist"  # Vite uses 'dist' instead of 'build'
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.8.2"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"